export const queryKeys = {
  auth: {
    all: ["auth"] as const,
    user: () => [...queryKeys.auth.all, "user"] as const,
    session: () => [...queryKeys.auth.all, "session"] as const,
  },
  dashboard: {
    all: ["dashboard"] as const,
    stats: () => [...queryKeys.dashboard.all, "stats"] as const,
    summary: () => [...queryKeys.dashboard.all, "summary"] as const,
  },
  analytics: {
    all: ["analytics"] as const,
    overview: () => [...queryKeys.analytics.all, "overview"] as const,
    occupancy: () => [...queryKeys.analytics.all, "occupancy"] as const,
    library: () => [...queryKeys.analytics.all, "library"] as const,
    canteen: () => [...queryKeys.analytics.all, "canteen"] as const,
    shuttle: () => [...queryKeys.analytics.all, "shuttle"] as const,
    maintenance: () => [...queryKeys.analytics.all, "maintenance"] as const,
    events: () => [...queryKeys.analytics.all, "events"] as const,
  },
  buildings: {
    all: ["buildings"] as const,
    list: () => [...queryKeys.buildings.all, "list"] as const,
    detail: (id: string) => [...queryKeys.buildings.all, "detail", id] as const,
  },
  rooms: {
    all: (buildingId?: string) => buildingId ? ["buildings", buildingId, "rooms"] as const : ["rooms"] as const,
    list: (buildingId: string) => [...queryKeys.rooms.all(buildingId), "list"] as const,
    detail: (buildingId: string, roomId: string) => [...queryKeys.rooms.all(buildingId), "detail", roomId] as const,
    occupancy: () => ["occupancy", "rooms"] as const,
  },
  library: {
    all: ["library"] as const,
    books: () => [...queryKeys.library.all, "books"] as const,
    borrowed: () => [...queryKeys.library.all, "borrowed"] as const,
  },
  canteen: {
    all: ["canteen"] as const,
    queues: () => [...queryKeys.canteen.all, "queues"] as const,
  },
  shuttle: {
    all: ["shuttle"] as const,
    routes: () => [...queryKeys.shuttle.all, "routes"] as const,
    schedule: () => [...queryKeys.shuttle.all, "schedule"] as const,
    locations: () => [...queryKeys.shuttle.all, "locations"] as const,
  },
  events: {
    all: ["events"] as const,
    list: () => ["events", "list"] as const,
    upcoming: () => ["events", "upcoming"] as const,
    detail: (id: string) => ["events", "detail", id] as const,
    byStatus: (status: string) => ["events", "status", status] as const,
    byCategory: (category: string) => ["events", "category", category] as const,
    byBuilding: (buildingId: string) => ["events", "building", buildingId] as const,
    byRoom: (roomId: string) => ["events", "room", roomId] as const,
    byRange: (start: string, end: string) => ["events", "range", start, end] as const,
  },
  maintenance: {
    all: ["maintenance"] as const,
    requests: () => [...queryKeys.maintenance.all, "requests"] as const,
    my: ["maintenance", "my"] as const,
    byStatus: (status: string) => ["maintenance", "status", status] as const,
    byPriority: (priority: string) => ["maintenance", "priority", priority] as const,
    byBuilding: (buildingId: string) => ["maintenance", "building", buildingId] as const,
    byRoom: (roomId: string) => ["maintenance", "room", roomId] as const,
    detail: (id: string) => ["maintenance", "detail", id] as const,
  },
  notifications: {
    all: ["notifications"] as const,
    list: () => [...queryKeys.notifications.all, "list"] as const,
  },
  // Imported Developer 3 Keys
  librarySeats: {
    all: (libraryId?: string) => ["librarySeats", { libraryId: libraryId ?? null }] as const,
    available: (libraryId?: string) => ["librarySeats", "available", { libraryId: libraryId ?? null }] as const,
    occupied: (libraryId?: string) => ["librarySeats", "occupied", { libraryId: libraryId ?? null }] as const,
    detail: (id: string) => ["librarySeats", "detail", id] as const,
  },
  canteens: {
    all: (buildingId?: string) => ["canteens", { buildingId: buildingId ?? null }] as const,
    byName: (name: string) => ["canteens", "search", name] as const,
    detail: (id: string) => ["canteens", "detail", id] as const,
  },
  canteenQueues: {
    all: ["canteenQueues"] as const,
    detail: (id: string) => ["canteenQueues", "detail", id] as const,
    byCanteen: (canteenId: string) => ["canteenQueues", "canteen", canteenId] as const,
  },
  shuttles: {
    all: ["shuttles"] as const,
    active: ["shuttles", "active"] as const,
    byStatus: (status: string) => ["shuttles", "status", status] as const,
    detail: (id: string) => ["shuttles", "detail", id] as const,
  },
  shuttleLocations: {
    allCurrent: ["shuttleLocations"] as const,
    detail: (id: string) => ["shuttleLocations", "detail", id] as const,
    latest: (shuttleId: string) => ["shuttleLocations", "latest", shuttleId] as const,
    history: (shuttleId: string) => ["shuttleLocations", "history", shuttleId] as const,
  },
} as const;
